### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by clalovelivesky** [kosaka-bun/tray-icon-runner#1]
你好，已用，喜欢该程序，在使用过程中有遇到希望改进的地方:
    我在使用upupoo的桌面蜂窝收纳程序，该程序没有任务栏图标，也没有托盘图标，资源管理器只能看到其后台进程。其运作效果是生成一个收藏夹贴在桌面上，有点像桌面歌词一样。
    使用 TrayIconRunner 对其创建托盘图标成功，但点击该托盘图标没反应，右击该图标消失，程序本身没产生任何变化。故希望建议几点改进方向：
    1、增加托盘图标的右键菜单，我希望在托盘处操作让软件退出进程。
    2、默认生成的图标不好看，能否.tir文件中增加属性，让我设置ico路径自定义托盘图标
    3、如何绑定程序，即我的软件启动时，自动执行.tir文件并生成托盘图标？
如需详细了解我的使用情况，请邮箱联系：1341607615@qq.com
期待回复和改进，谢谢

**Comment by kosaka-bun** [comment]
感谢您使用这个工具，以下是针对您提出的问题所作的回答：

1. 设计之初有打算在托盘图标上添加“退出”菜单项，但考虑到在代码中退出进程几乎只能强制结束，很难实现安全地退出一个程序（如虚拟机在退出时需要先关机或挂起），故没有去添加这一菜单项。
2. 这是个不错的建议，但就该工具本身的性质而言，这并不是一个迫切需要实现的功能。
3. 您似乎是想在直接双击运行程序原本的可执行文件（如`.bat`、`.exe`等）时，不首先启动它，而是先生成托盘图标后，再启动程序。如果您确实是这么认为的，那么这或许不是一个能实现的功能，因为Windows对`.exe`文件的关联似乎是不可更改的。

**Comment by kosaka-bun** [comment]
根据您对“upupoo的桌面蜂窝收纳程序”的描述，可能是由于该程序并不存在主窗口，因此该工具无法获取到其主窗口句柄，使得它不能配合该收纳程序进行使用。

需要注意的是，该工具的功能是将一些持续运行的程序的主窗口隐藏，然后提供一个托盘图标用于将被隐藏的主窗口唤出，以防止那些程序的主窗口影响用户的使用。它并非是一个用于监视和控制其他应用程序的工具，因此它不能脱离窗口进行使用，也没有提供功能丰富的托盘图标菜单。

**Comment by clalovelivesky** [comment]
明白了，谢谢你的回复
